AOSP/DeskClock - Move API level 24 for Alarm, Timer and basic functionality to work.
DeskClock is generating the following error. To fix the issue, moved the API level to 24.
  keyboard_arrow_down
  android.app.RemoteServiceException: Bad notification for startForeground

  android.app.RemoteServiceException
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run
  at com.android.internal.os.ZygoteInit.main
    at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:1930)

BUG: 199820402
BUG: 199822689
BUG: 199820401

Test: manual - Tested the DeskClock UI manually and tested the alarm.

+ Verified by setting up the alaram, lock the screen and waiting for the alarm to go off.
+ Verified timer is going off.
+ Verified screen saver settings is set to DeskClock's time.
+ Verified all of the above bugs are fixed.

$ make -j 40

$ adb install -r out/target/product/bonito/product/app/DeskClock/DeskClock.apk

$ adb install -d -r out/target/product/bonito/testcases/DeskClockTests/arm64/DeskClockTests.apk

$ adb shell am instrument -w com.android.deskclock.tests

com.android.deskclock.ringtone.RingtonePickerActivityTest:....
com.android.deskclock.timer.ExpiredTimersActivityTest:.
com.android.deskclock.timer.TimerFragmentTest:.........................................
com.android.deskclock.timer.TimerItemFragmentTest:.
com.android.deskclock.timer.TimerServiceTest:..
com.android.deskclock.timer.TimerSetupViewTest:........
com.android.deskclock.uidata.FormattedStringModelTest:...
com.android.deskclock.uidata.PeriodicCallbackModelTest:....
com.android.deskclock.uidata.TabModelTest:..
com.android.deskclock.worldclock.CitySelectionActivityTest:..

Time: 87.313

OK (68 tests)

+ Verified by setting up the alaram, lock the screen and waiting for the alarm to go off.

Change-Id: Id2e48481c0e5b04fb33a368a2804a117983586cf